### ISSUE TITLE
[Bug] Some env variables are missing in the docker images

### ISSUE THREAD

**Issue by im-samwong** [XavierGuertin/WildfireVisualizationProject#235]
#### **Description**  
Some environment variables are missing in the built Docker images, causing issues when running the application. While `NEXT_PUBLIC_BACKEND_URL` is passed correctly as a build argument, other required environment variables are not included, leading to incorrect or missing configurations in the frontend.  

#### **Expected Behavior**  
All required environment variables should be available in the Docker container after the image is built, ensuring proper connectivity between services.  

#### **Current Behavior**  
Only `NEXT_PUBLIC_BACKEND_URL` is being set correctly. The following variables are missing or not properly passed into the container:  

- `NEXT_PUBLIC_BACKEND_URL=http://localhost:8080`  
- `NEXT_PUBLIC_GEOSERVER_URL=http://localhost:8090/geoserver/Default/wms`  
- `NEXT_PUBLIC_TILESERVER_URL=http://localhost:8081/data/OAM-World-1-8-min-J80`  

This causes issues with frontend map rendering and API calls, as the application cannot reach the required services.  

#### **Steps to Reproduce**  
1. Build the frontend Docker image:  
   ```sh
   docker-compose build frontend
   ```  
2. Run the container:  
   ```sh
   docker-compose up frontend
   ```  
3. Inside the container, check for missing environment variables:  
   ```sh
   docker exec -it <frontend-container-id> env | grep NEXT_PUBLIC
   ```  
4. Observe that only `NEXT_PUBLIC_BACKEND_URL` is set while others are missing.  

#### **Possible Causes**  
- Other environment variables are **not passed as build arguments**.  
- Missing `ARG` and `ENV` declarations in the `Dockerfile`.  

#### **Proposed Fix**  
Modify the `Dockerfile` to explicitly include all required environment variables:  
```dockerfile
# Accept build arguments  
ARG NEXT_PUBLIC_BACKEND_URL  
ARG NEXT_PUBLIC_GEOSERVER_URL  
ARG NEXT_PUBLIC_TILESERVER_URL  

# Set environment variables  
ENV NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}  
ENV NEXT_PUBLIC_GEOSERVER_URL=${NEXT_PUBLIC_GEOSERVER_URL}  
ENV NEXT_PUBLIC_TILESERVER_URL=${NEXT_PUBLIC_TILESERVER_URL}  

# Build the frontend app using the nx target  
RUN npx nx run frontend:build  
```

Additionally, ensure `docker-compose.yml` passes these values as build arguments:  
```yaml
frontend:
  build:
    context: .
    dockerfile: ./apps/frontend/Dockerfile
    args:
      NEXT_PUBLIC_BACKEND_URL: http://localhost:8080
      NEXT_PUBLIC_GEOSERVER_URL: http://localhost:8090/geoserver/Default/wms
      NEXT_PUBLIC_TILESERVER_URL: http://localhost:8081/data/OAM-World-1-8-min-J80
```

#### **Impact**  
-  **Frontend fails to correctly connect to backend, GeoServer, and TileServer.**  
-  **Map layers may not load properly due to missing TileServer URL.**  
-  **API requests may be directed to incorrect endpoints.**  

#### **Priority**: High  
This issue **blocks proper frontend functionality** and needs to be addressed for correct environment configuration in Docker.
